In [2]:
import torch

In [3]:
t1 = torch.randint(0, 10, (3, 4))
t2 = torch.randint(0, 10, (3, 4))
print(f"t1是\n{t1}和t2是\n{t2}打印的结果为[\n{(t1+t2-2)*2}")


t1是
tensor([[2, 6, 6, 0],
        [3, 3, 0, 4],
        [7, 7, 4, 9]])和t2是
tensor([[4, 4, 8, 3],
        [5, 8, 1, 0],
        [2, 2, 2, 2]])打印的结果为[
tensor([[ 8, 16, 24,  2],
        [12, 18, -2,  4],
        [14, 14,  8, 18]])


In [4]:
t1 = torch.arange(12).reshape(3,4)
t2 = torch.randint(0, 10, (3, 4))
print(f't1Xt2是\n{t1*t2}')
t2 = t2.view(4,3)
print(f't2:\n{t2}, shape:{t2.shape}')
print(f't1@t2是\n{t1@t2}')

t1Xt2是
tensor([[ 0,  6, 18,  9],
        [ 8, 25, 30,  7],
        [ 0, 81, 50, 99]])
t2:
tensor([[9, 6, 9],
        [3, 2, 5],
        [5, 1, 0],
        [9, 5, 9]]), shape:torch.Size([4, 3])
t1@t2是
tensor([[ 40,  19,  32],
        [144,  75, 124],
        [248, 131, 216]])


In [5]:
t1 = torch.randint(0, 10, (3, 4)).to(torch.float32).mean()
print(f't1:\n{t1}, shape:{t1.shape}')
t2 = torch.randint(0, 10, (3, 4)).to(torch.float32)
print(f't2:\n{t2}, shape:{t2.shape}')
t3= t2.mean(dim=0)
print(f't3:\n{t3}, shape:{t3.shape}')

t1:
6.083333492279053, shape:torch.Size([])
t2:
tensor([[0., 6., 9., 8.],
        [0., 4., 0., 1.],
        [2., 4., 5., 2.]]), shape:torch.Size([3, 4])
t3:
tensor([0.6667, 4.6667, 4.6667, 3.6667]), shape:torch.Size([4])


In [6]:
t1 = torch.randint(0, 10, (3, 4))
print(f't1:\n{t1}, shape:{t1.shape}')
# 获取第二个轴,索引为1的所有数据
t2 = t1[:,1]
print(f't2:\n{t2}, shape:{t2.shape}')
# 获取第二个轴 索引为1大于5的元素对应的第一个轴的数据
t2 = t1[t1[:,1]>5]
print(f't3:\n{t2}, shape:{t2.shape}')
#

t1:
tensor([[8, 8, 0, 5],
        [8, 9, 8, 4],
        [3, 7, 5, 6]]), shape:torch.Size([3, 4])
t2:
tensor([8, 9, 7]), shape:torch.Size([3])
t3:
tensor([[8, 8, 0, 5],
        [8, 9, 8, 4],
        [3, 7, 5, 6]]), shape:torch.Size([3, 4])


In [7]:
t1 = torch.randint(0, 10, (3, 4))
t2 = torch.randint(0, 10, (3, 4))
t1= t1.reshape(-1,3)
t2= t2.reshape(-1,3)
print(f't1:\n{t1}, t2:\n{t2}')
t3 = torch.cat([t1, t2], dim=0)
print(f't3:\n{t3}, shape:{t3.shape}')

t1:
tensor([[8, 6, 2],
        [1, 2, 2],
        [7, 7, 8],
        [7, 5, 8]]), t2:
tensor([[2, 4, 2],
        [6, 9, 3],
        [5, 4, 9],
        [2, 8, 9]])
t3:
tensor([[8, 6, 2],
        [1, 2, 2],
        [7, 7, 8],
        [7, 5, 8],
        [2, 4, 2],
        [6, 9, 3],
        [5, 4, 9],
        [2, 8, 9]]), shape:torch.Size([8, 3])


In [8]:
# 创建一个形状为(3)的随机张量w
w = torch.randint(0, 10, (3,), requires_grad=True, dtype=torch.float32)
print(f'w:\n{w}, shape:{w.shape}')
loss = w**2 +20
loss.mean().backward()
print(f'w.grad:\n{w.grad}, shape:{w.grad.shape}')
w.data = w.data - 0.01*w.grad
print(f'w:\n{w}, shape:{w.shape}')

w:
tensor([8., 1., 6.], requires_grad=True), shape:torch.Size([3])
w.grad:
tensor([5.3333, 0.6667, 4.0000]), shape:torch.Size([3])
w:
tensor([7.9467, 0.9933, 5.9600], requires_grad=True), shape:torch.Size([3])
